#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v2
# autospec commit: f032afc
#
Name     : pcp
Version  : 6.0.5
Release  : 15
URL      : https://github.com/performancecopilot/pcp/archive/6.0.5/pcp-6.0.5.tar.gz
Source0  : https://github.com/performancecopilot/pcp/archive/6.0.5/pcp-6.0.5.tar.gz
Summary  : System-level performance monitoring and performance management
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-3.0 GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1 LGPL-2.1+ MIT
Requires: pcp-bin = %{version}-%{release}
Requires: pcp-config = %{version}-%{release}
Requires: pcp-data = %{version}-%{release}
Requires: pcp-lib = %{version}-%{release}
Requires: pcp-libexec = %{version}-%{release}
Requires: pcp-license = %{version}-%{release}
Requires: pcp-man = %{version}-%{release}
Requires: pcp-perl = %{version}-%{release}
Requires: pcp-python = %{version}-%{release}
Requires: pcp-python3 = %{version}-%{release}
Requires: pcp-services = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : buildreq-kde
BuildRequires : flex
BuildRequires : inkscape
BuildRequires : ncurses-dev
BuildRequires : nspr-dev
BuildRequires : nss-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(hwloc)
BuildRequires : pkgconfig(libbpf)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libprofiler)
BuildRequires : pkgconfig(libsasl2)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libuv)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(zlib)
BuildRequires : pypi(pylint)
BuildRequires : python3-dev
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Performance Co-Pilot (PCP) provides a framework and services to support
system-level performance monitoring and performance management.

The PCP open source release provides a unifying abstraction for all of
the interesting performance data in a system, and allows client
applications to easily retrieve and process any subset of that data.

%package bin
Summary: bin components for the pcp package.
Group: Binaries
Requires: pcp-data = %{version}-%{release}
Requires: pcp-libexec = %{version}-%{release}
Requires: pcp-config = %{version}-%{release}
Requires: pcp-license = %{version}-%{release}
Requires: pcp-services = %{version}-%{release}

%description bin
bin components for the pcp package.


%package config
Summary: config components for the pcp package.
Group: Default

%description config
config components for the pcp package.


%package data
Summary: data components for the pcp package.
Group: Data

%description data
data components for the pcp package.


%package dev
Summary: dev components for the pcp package.
Group: Development
Requires: pcp-lib = %{version}-%{release}
Requires: pcp-bin = %{version}-%{release}
Requires: pcp-data = %{version}-%{release}
Provides: pcp-devel = %{version}-%{release}
Requires: pcp = %{version}-%{release}

%description dev
dev components for the pcp package.


%package doc
Summary: doc components for the pcp package.
Group: Documentation
Requires: pcp-man = %{version}-%{release}

%description doc
doc components for the pcp package.


%package lib
Summary: lib components for the pcp package.
Group: Libraries
Requires: pcp-data = %{version}-%{release}
Requires: pcp-libexec = %{version}-%{release}
Requires: pcp-license = %{version}-%{release}

%description lib
lib components for the pcp package.


%package libexec
Summary: libexec components for the pcp package.
Group: Default
Requires: pcp-config = %{version}-%{release}
Requires: pcp-license = %{version}-%{release}

%description libexec
libexec components for the pcp package.


%package license
Summary: license components for the pcp package.
Group: Default

%description license
license components for the pcp package.


%package man
Summary: man components for the pcp package.
Group: Default

%description man
man components for the pcp package.


%package perl
Summary: perl components for the pcp package.
Group: Default
Requires: pcp = %{version}-%{release}

%description perl
perl components for the pcp package.


%package python
Summary: python components for the pcp package.
Group: Default
Requires: pcp-python3 = %{version}-%{release}

%description python
python components for the pcp package.


%package python3
Summary: python3 components for the pcp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pcp package.


%package services
Summary: services components for the pcp package.
Group: Systemd services
Requires: systemd

%description services
services components for the pcp package.


%prep
%setup -q -n pcp-6.0.5
cd %{_builddir}/pcp-6.0.5

%build
## build_prepend content
unset AR
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697578769
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1697578769
rm -rf %{buildroot}
## install_prepend content
export DIST_ROOT=$RPM_BUILD_ROOT
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/pcp
cp %{_builddir}/pcp-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pcp/5d5da1000ec36c87ff28d1208cc89fa575f8675f || :
cp %{_builddir}/pcp-%{version}/build/mac/installer-resources/License.html %{buildroot}/usr/share/package-licenses/pcp/488640bbc156f41a2d4c993008c5c72ddc4a1219 || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/Nordix/hiredis-cluster/COPYING %{buildroot}/usr/share/package-licenses/pcp/2b643890566d601c71f17a60bade7af58bb1a331 || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/benhoyt/inih/LICENSE.txt %{buildroot}/usr/share/package-licenses/pcp/d097282eb6f05d825f591cef06bac3654b58feba || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/htop-dev/htop/COPYING %{buildroot}/usr/share/package-licenses/pcp/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/iovisor/bcc/LICENSE.txt %{buildroot}/usr/share/package-licenses/pcp/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/libbpf/bpftool/LICENSE.BSD-2-Clause %{buildroot}/usr/share/package-licenses/pcp/34c5034377edef1080538bd0d4f5cf9b78e22dff || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/libbpf/bpftool/LICENSE.GPL-2.0 %{buildroot}/usr/share/package-licenses/pcp/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/libbpf/bpftool/libbpf/LICENSE.BSD-2-Clause %{buildroot}/usr/share/package-licenses/pcp/419ec3c0b11c7d22472ea99c03c347413a4ea406 || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/libbpf/bpftool/libbpf/LICENSE.LGPL-2.1 %{buildroot}/usr/share/package-licenses/pcp/91c66db733cf0ff2b3216ec4223b940daf6b26d4 || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/mnunberg/jsonsl/LICENSE %{buildroot}/usr/share/package-licenses/pcp/77b27c166eb1c7fa55288331b53f9c72b067e3c8 || :
cp %{_builddir}/pcp-%{version}/vendor/github.com/redis/hiredis/COPYING %{buildroot}/usr/share/package-licenses/pcp/e9c1298de98016808910005a33de3a5f25dce05e || :
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/dstat
## install_append content
rm -rf %{buildroot}/var
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/collectl2pcp
/usr/bin/dbpmda
/usr/bin/ganglia2pcp
/usr/bin/genpmda
/usr/bin/iostat2pcp
/usr/bin/mrtg2pcp
/usr/bin/pcp
/usr/bin/pcp2csv
/usr/bin/pcp2graphite
/usr/bin/pcp2json
/usr/bin/pcp2spark
/usr/bin/pcp2xml
/usr/bin/pcp2zabbix
/usr/bin/pmafm
/usr/bin/pmchart
/usr/bin/pmclient
/usr/bin/pmclient_fg
/usr/bin/pmconfirm
/usr/bin/pmdate
/usr/bin/pmdbg
/usr/bin/pmdiff
/usr/bin/pmdumplog
/usr/bin/pmdumptext
/usr/bin/pmerr
/usr/bin/pmevent
/usr/bin/pmfind
/usr/bin/pmgenmap
/usr/bin/pmie
/usr/bin/pmie2col
/usr/bin/pmieconf
/usr/bin/pmiectl
/usr/bin/pminfo
/usr/bin/pmiostat
/usr/bin/pmjson
/usr/bin/pmlc
/usr/bin/pmlogcheck
/usr/bin/pmlogconf
/usr/bin/pmlogctl
/usr/bin/pmlogdump
/usr/bin/pmlogextract
/usr/bin/pmlogger
/usr/bin/pmloglabel
/usr/bin/pmlogmv
/usr/bin/pmlogpaste
/usr/bin/pmlogsize
/usr/bin/pmlogsummary
/usr/bin/pmmessage
/usr/bin/pmprobe
/usr/bin/pmpython
/usr/bin/pmquery
/usr/bin/pmrep
/usr/bin/pmrepconf
/usr/bin/pmsearch
/usr/bin/pmseries
/usr/bin/pmsocks
/usr/bin/pmstat
/usr/bin/pmstore
/usr/bin/pmtime
/usr/bin/pmtrace
/usr/bin/pmval
/usr/bin/sar2pcp
/usr/bin/sheet2pcp

%files config
%defattr(-,root,root,-)
/usr/lib/sysusers.d/pcp-testsuite.conf
/usr/lib/sysusers.d/pcp.conf

%files data
%defattr(-,root,root,-)
/usr/share/applications/pmchart.desktop
/usr/share/bash-completion/completions/pcp
/usr/share/bash-completion/completions/pcp2graphite
/usr/share/bash-completion/completions/pcp2json
/usr/share/bash-completion/completions/pcp2spark
/usr/share/bash-completion/completions/pcp2xml
/usr/share/bash-completion/completions/pcp2zabbix
/usr/share/bash-completion/completions/pmdumplog
/usr/share/bash-completion/completions/pmdumptext
/usr/share/bash-completion/completions/pmevent
/usr/share/bash-completion/completions/pmfind
/usr/share/bash-completion/completions/pmie
/usr/share/bash-completion/completions/pmie2col
/usr/share/bash-completion/completions/pmiectl
/usr/share/bash-completion/completions/pminfo
/usr/share/bash-completion/completions/pmjson
/usr/share/bash-completion/completions/pmlc
/usr/share/bash-completion/completions/pmlogcheck
/usr/share/bash-completion/completions/pmlogctl
/usr/share/bash-completion/completions/pmlogextract
/usr/share/bash-completion/completions/pmlogger
/usr/share/bash-completion/completions/pmloglabel
/usr/share/bash-completion/completions/pmlogpaste
/usr/share/bash-completion/completions/pmlogreduce
/usr/share/bash-completion/completions/pmlogsize
/usr/share/bash-completion/completions/pmlogsummary
/usr/share/bash-completion/completions/pmprobe
/usr/share/bash-completion/completions/pmrep
/usr/share/bash-completion/completions/pmseries
/usr/share/bash-completion/completions/pmstat
/usr/share/bash-completion/completions/pmstore
/usr/share/bash-completion/completions/pmval
/usr/share/icons/hicolor/128x128/apps/pmchart.png
/usr/share/icons/hicolor/128x128/apps/pmtime.png
/usr/share/icons/hicolor/16x16/apps/pmchart.png
/usr/share/icons/hicolor/16x16/apps/pmtime.png
/usr/share/icons/hicolor/22x22/apps/pmchart.png
/usr/share/icons/hicolor/22x22/apps/pmtime.png
/usr/share/icons/hicolor/24x24/apps/pmchart.png
/usr/share/icons/hicolor/24x24/apps/pmtime.png
/usr/share/icons/hicolor/256x256/apps/pmchart.png
/usr/share/icons/hicolor/256x256/apps/pmtime.png
/usr/share/icons/hicolor/32x32/apps/pmchart.png
/usr/share/icons/hicolor/32x32/apps/pmtime.png
/usr/share/icons/hicolor/48x48/apps/pmchart.png
/usr/share/icons/hicolor/48x48/apps/pmtime.png
/usr/share/icons/hicolor/64x64/apps/pmchart.png
/usr/share/icons/hicolor/64x64/apps/pmtime.png
/usr/share/icons/hicolor/scalable/apps/pmchart.svg
/usr/share/icons/hicolor/scalable/apps/pmtime.svg
/usr/share/pcp-gui/pixmaps/pmchart.png
/usr/share/pcp-gui/pixmaps/pmtime.png
/usr/share/pcp/demos/mmv/Makefile
/usr/share/pcp/demos/mmv/README
/usr/share/pcp/demos/mmv/acme.c
/usr/share/pcp/demos/mmv/mmvdump.c
/usr/share/pcp/demos/pmclient/Makefile
/usr/share/pcp/demos/pmclient/README
/usr/share/pcp/demos/pmclient/pmclient.c
/usr/share/pcp/demos/pmclient/pmclient_fg.c
/usr/share/pcp/demos/pmclient/pmclient_fg.python
/usr/share/pcp/demos/pmclient/pmlogger.config
/usr/share/pcp/demos/pmclient/pmnsmap.spec
/usr/share/pcp/demos/procmemstat/Makefile
/usr/share/pcp/demos/procmemstat/README
/usr/share/pcp/demos/procmemstat/pmnsmap.spec
/usr/share/pcp/demos/procmemstat/procmemstat.c
/usr/share/pcp/demos/trace/Makefile
/usr/share/pcp/demos/trace/Makefile.stub
/usr/share/pcp/demos/trace/README
/usr/share/pcp/demos/trace/app1.c
/usr/share/pcp/demos/trace/app2.c
/usr/share/pcp/demos/trace/app3.c
/usr/share/pcp/demos/trace/fapp1.f
/usr/share/pcp/demos/trace/japp1.java
/usr/share/pcp/demos/trace/pmtrace.c
/usr/share/pcp/demos/trace/stub.c
/usr/share/pcp/demos/tutorials/cpuperf.tar.gz
/usr/share/pcp/demos/tutorials/diskmodel.tar.gz
/usr/share/pcp/demos/tutorials/diskperf.tar.gz
/usr/share/pcp/demos/tutorials/pmie.tar.gz
/usr/share/pcp/demos/tutorials/pmview.tar.gz
/usr/share/pcp/examples/pcp2spark/PCP2SparkStreamCollector.python
/usr/share/pcp/examples/pcp2spark/README.md
/usr/share/pcp/examples/pmie/CPU
/usr/share/pcp/examples/pmie/DISK
/usr/share/pcp/examples/pmie/ENVIRON
/usr/share/pcp/examples/pmie/FILESYS
/usr/share/pcp/examples/pmie/NETWORK
/usr/share/pcp/examples/pmie/RAS
/usr/share/pcp/examples/pmie/README
/usr/share/pcp/examples/pmie/SWAP
/usr/share/pcp/examples/pmie/UAG
/usr/share/pcp/examples/pmie/UPM
/usr/share/pcp/examples/pmie/WEBREPORT
/usr/share/pcp/htop/columns/container
/usr/share/pcp/htop/columns/delayacct
/usr/share/pcp/htop/columns/fdcount
/usr/share/pcp/htop/columns/guest
/usr/share/pcp/htop/columns/memory
/usr/share/pcp/htop/columns/sched
/usr/share/pcp/htop/columns/swap
/usr/share/pcp/htop/columns/tcp
/usr/share/pcp/htop/columns/udp
/usr/share/pcp/htop/columns/wchan
/usr/share/pcp/htop/meters/entropy
/usr/share/pcp/htop/meters/freespace
/usr/share/pcp/htop/meters/ipc
/usr/share/pcp/htop/meters/locks
/usr/share/pcp/htop/meters/memcache
/usr/share/pcp/htop/meters/mysql
/usr/share/pcp/htop/meters/postfix
/usr/share/pcp/htop/meters/redis
/usr/share/pcp/htop/meters/tcp
/usr/share/pcp/lib/ReplacePmnsSubtree
/usr/share/pcp/lib/bashproc.sh
/usr/share/pcp/lib/lockpmns
/usr/share/pcp/lib/pmdaproc.sh
/usr/share/pcp/lib/rc-proc.sh
/usr/share/pcp/lib/rc-proc.sh.minimal
/usr/share/pcp/lib/unlockpmns
/usr/share/pcp/lib/utilproc.sh
/usr/share/pcp/zeroconf/pmlogger
/usr/share/zsh/site-functions/_pcp

%files dev
%defattr(-,root,root,-)
/usr/include/pcp/archive.h
/usr/include/pcp/builddefs
/usr/include/pcp/buildrules
/usr/include/pcp/config.h
/usr/include/pcp/config32.h
/usr/include/pcp/config64.h
/usr/include/pcp/configsz.h
/usr/include/pcp/deprecated.h
/usr/include/pcp/dict.h
/usr/include/pcp/fault.h
/usr/include/pcp/impl.h
/usr/include/pcp/import.h
/usr/include/pcp/ini.h
/usr/include/pcp/mmv_dev.h
/usr/include/pcp/mmv_stats.h
/usr/include/pcp/platform32.h
/usr/include/pcp/platform64.h
/usr/include/pcp/platform_defs.h
/usr/include/pcp/platformsz.h
/usr/include/pcp/pmafm.h
/usr/include/pcp/pmapi.h
/usr/include/pcp/pmda.h
/usr/include/pcp/pmdaroot.h
/usr/include/pcp/pmdbg.h
/usr/include/pcp/pmhttp.h
/usr/include/pcp/pmjson.h
/usr/include/pcp/pmtime.h
/usr/include/pcp/pmwebapi.h
/usr/include/pcp/sds.h
/usr/include/pcp/trace.h
/usr/include/pcp/trace_dev.h
/usr/lib64/libpcp.so
/usr/lib64/libpcp_archive.so
/usr/lib64/libpcp_fault.so
/usr/lib64/libpcp_gui.so
/usr/lib64/libpcp_import.so
/usr/lib64/libpcp_mmv.so
/usr/lib64/libpcp_pmda.so
/usr/lib64/libpcp_trace.so
/usr/lib64/libpcp_web.so
/usr/lib64/pkgconfig/libpcp.pc
/usr/lib64/pkgconfig/libpcp_archive.pc
/usr/lib64/pkgconfig/libpcp_import.pc
/usr/lib64/pkgconfig/libpcp_pmda.pc
/usr/share/man/man3/LOGIMPORT.3.gz
/usr/share/man/man3/PCP::LogImport.3
/usr/share/man/man3/PCP::LogSummary.3
/usr/share/man/man3/PCP::MMV.3
/usr/share/man/man3/PCP::PMDA.3
/usr/share/man/man3/PCPIntro.3.gz
/usr/share/man/man3/PMAPI.3.gz
/usr/share/man/man3/PMAPI_INTERNAL.3.gz
/usr/share/man/man3/PMDA.3.gz
/usr/share/man/man3/PMWEBAPI.3.gz
/usr/share/man/man3/QMC.3.gz
/usr/share/man/man3/QmcContext.3.gz
/usr/share/man/man3/QmcDesc.3.gz
/usr/share/man/man3/QmcGroup.3.gz
/usr/share/man/man3/QmcIndom.3.gz
/usr/share/man/man3/QmcMetric.3.gz
/usr/share/man/man3/QmcSource.3.gz
/usr/share/man/man3/__pmAFblock.3.gz
/usr/share/man/man3/__pmAFisempty.3.gz
/usr/share/man/man3/__pmAFregister.3.gz
/usr/share/man/man3/__pmAFsetup.3.gz
/usr/share/man/man3/__pmAFunblock.3.gz
/usr/share/man/man3/__pmAFunregister.3.gz
/usr/share/man/man3/__pmAddIPC.3.gz
/usr/share/man/man3/__pmConnectLogger.3.gz
/usr/share/man/man3/__pmControlLog.3.gz
/usr/share/man/man3/__pmConvertHighResTime.3.gz
/usr/share/man/man3/__pmConvertTime.3.gz
/usr/share/man/man3/__pmDiscoverServicesWithOptions.3.gz
/usr/share/man/man3/__pmEquivInDom.3.gz
/usr/share/man/man3/__pmFdLookupIPC.3.gz
/usr/share/man/man3/__pmFreeAttrsSpec.3.gz
/usr/share/man/man3/__pmFreeHostAttrsSpec.3.gz
/usr/share/man/man3/__pmFreeHostSpec.3.gz
/usr/share/man/man3/__pmFreeProfile.3.gz
/usr/share/man/man3/__pmLocalPMDA.3.gz
/usr/share/man/man3/__pmLogMetaTypeStr.3.gz
/usr/share/man/man3/__pmLogMetaTypeStr_r.3.gz
/usr/share/man/man3/__pmLogWriteMark.3.gz
/usr/share/man/man3/__pmLookupIPC.3.gz
/usr/share/man/man3/__pmMktime.3.gz
/usr/share/man/man3/__pmOverrideLastFd.3.gz
/usr/share/man/man3/__pmParseCtime.3.gz
/usr/share/man/man3/__pmParseDebug.3.gz
/usr/share/man/man3/__pmParseHighResTime.3.gz
/usr/share/man/man3/__pmParseHostAttrsSpec.3.gz
/usr/share/man/man3/__pmParseHostSpec.3.gz
/usr/share/man/man3/__pmParseTime.3.gz
/usr/share/man/man3/__pmPrintIPC.3.gz
/usr/share/man/man3/__pmProcessAddArg.3.gz
/usr/share/man/man3/__pmProcessExec.3.gz
/usr/share/man/man3/__pmProcessPipe.3.gz
/usr/share/man/man3/__pmProcessPipeClose.3.gz
/usr/share/man/man3/__pmProcessUnpickArgs.3.gz
/usr/share/man/man3/__pmResetIPC.3.gz
/usr/share/man/man3/__pmServerNotifyServiceManagerReady.3.gz
/usr/share/man/man3/__pmServerNotifyServiceManagerStopping.3.gz
/usr/share/man/man3/__pmSetDebugBits.3.gz
/usr/share/man/man3/__pmUnparseHostAttrsSpec.3.gz
/usr/share/man/man3/__pmUnparseHostSpec.3.gz
/usr/share/man/man3/mmv_inc.3.gz
/usr/share/man/man3/mmv_inc_atomvalue.3.gz
/usr/share/man/man3/mmv_inc_value.3.gz
/usr/share/man/man3/mmv_lookup_value_desc.3.gz
/usr/share/man/man3/mmv_set.3.gz
/usr/share/man/man3/mmv_set_atomvalue.3.gz
/usr/share/man/man3/mmv_set_value.3.gz
/usr/share/man/man3/mmv_stats2_init.3.gz
/usr/share/man/man3/mmv_stats_init.3.gz
/usr/share/man/man3/mmv_stats_registry.3.gz
/usr/share/man/man3/mmv_stats_start.3.gz
/usr/share/man/man3/mmv_stats_stop.3.gz
/usr/share/man/man3/pmAF.3.gz
/usr/share/man/man3/pmAddDerived.3.gz
/usr/share/man/man3/pmAddDerivedMetric.3.gz
/usr/share/man/man3/pmAddDerivedText.3.gz
/usr/share/man/man3/pmAddProfile.3.gz
/usr/share/man/man3/pmAtomStr.3.gz
/usr/share/man/man3/pmAtomStr_r.3.gz
/usr/share/man/man3/pmClearDebug.3.gz
/usr/share/man/man3/pmClearFetchGroup.3.gz
/usr/share/man/man3/pmConvScale.3.gz
/usr/share/man/man3/pmCreateFetchGroup.3.gz
/usr/share/man/man3/pmCtime.3.gz
/usr/share/man/man3/pmDelProfile.3.gz
/usr/share/man/man3/pmDerivedControl.3.gz
/usr/share/man/man3/pmDerivedErrStr.3.gz
/usr/share/man/man3/pmDestroyContext.3.gz
/usr/share/man/man3/pmDestroyFetchGroup.3.gz
/usr/share/man/man3/pmDiscoverClose.3.gz
/usr/share/man/man3/pmDiscoverServices.3.gz
/usr/share/man/man3/pmDiscoverSetConfiguration.3.gz
/usr/share/man/man3/pmDiscoverSetEventLoop.3.gz
/usr/share/man/man3/pmDiscoverSetMetricRegistry.3.gz
/usr/share/man/man3/pmDiscoverSetSlots.3.gz
/usr/share/man/man3/pmDiscoverSetup.3.gz
/usr/share/man/man3/pmDupContext.3.gz
/usr/share/man/man3/pmErrStr.3.gz
/usr/share/man/man3/pmErrStr_r.3.gz
/usr/share/man/man3/pmEventFlagsStr.3.gz
/usr/share/man/man3/pmEventFlagsStr_r.3.gz
/usr/share/man/man3/pmExtendFetchGroup_event.3.gz
/usr/share/man/man3/pmExtendFetchGroup_indom.3.gz
/usr/share/man/man3/pmExtendFetchGroup_item.3.gz
/usr/share/man/man3/pmExtendFetchGroup_timespec.3.gz
/usr/share/man/man3/pmExtendFetchGroup_timestamp.3.gz
/usr/share/man/man3/pmExtendFetchGroup_timeval.3.gz
/usr/share/man/man3/pmExtractValue.3.gz
/usr/share/man/man3/pmFetch.3.gz
/usr/share/man/man3/pmFetchArchive.3.gz
/usr/share/man/man3/pmFetchGroup.3.gz
/usr/share/man/man3/pmFetchHighRes.3.gz
/usr/share/man/man3/pmFetchHighResArchive.3.gz
/usr/share/man/man3/pmFreeEventResult.3.gz
/usr/share/man/man3/pmFreeHighResEventResult.3.gz
/usr/share/man/man3/pmFreeHighResResult.3.gz
/usr/share/man/man3/pmFreeLabelSets.3.gz
/usr/share/man/man3/pmFreeMetricSpec.3.gz
/usr/share/man/man3/pmFreeOptions.3.gz
/usr/share/man/man3/pmFreeResult.3.gz
/usr/share/man/man3/pmGetAPIConfig.3.gz
/usr/share/man/man3/pmGetArchiveEnd.3.gz
/usr/share/man/man3/pmGetArchiveLabel.3.gz
/usr/share/man/man3/pmGetChildren.3.gz
/usr/share/man/man3/pmGetChildrenStatus.3.gz
/usr/share/man/man3/pmGetClusterLabels.3.gz
/usr/share/man/man3/pmGetConfig.3.gz
/usr/share/man/man3/pmGetContextHostName.3.gz
/usr/share/man/man3/pmGetContextHostName_r.3.gz
/usr/share/man/man3/pmGetContextLabels.3.gz
/usr/share/man/man3/pmGetContextOptions.3.gz
/usr/share/man/man3/pmGetDerivedControl.3.gz
/usr/share/man/man3/pmGetDomainLabels.3.gz
/usr/share/man/man3/pmGetFetchGroupContext.3.gz
/usr/share/man/man3/pmGetHighResArchiveEnd.3.gz
/usr/share/man/man3/pmGetHighResArchiveLabel.3.gz
/usr/share/man/man3/pmGetHostName.3.gz
/usr/share/man/man3/pmGetInDom.3.gz
/usr/share/man/man3/pmGetInDomArchive.3.gz
/usr/share/man/man3/pmGetInDomLabels.3.gz
/usr/share/man/man3/pmGetInstancesLabels.3.gz
/usr/share/man/man3/pmGetItemLabels.3.gz
/usr/share/man/man3/pmGetOptionalConfig.3.gz
/usr/share/man/man3/pmGetOptions.3.gz
/usr/share/man/man3/pmGetPMNSLocation.3.gz
/usr/share/man/man3/pmGetProgname.3.gz
/usr/share/man/man3/pmGetUsername.3.gz
/usr/share/man/man3/pmGetVersion.3.gz
/usr/share/man/man3/pmHighResFetch.3.gz
/usr/share/man/man3/pmIDStr.3.gz
/usr/share/man/man3/pmIDStr_r.3.gz
/usr/share/man/man3/pmID_build.3.gz
/usr/share/man/man3/pmID_cluster.3.gz
/usr/share/man/man3/pmID_domain.3.gz
/usr/share/man/man3/pmID_item.3.gz
/usr/share/man/man3/pmInDomStr.3.gz
/usr/share/man/man3/pmInDomStr_r.3.gz
/usr/share/man/man3/pmInDom_build.3.gz
/usr/share/man/man3/pmInDom_domain.3.gz
/usr/share/man/man3/pmInDom_serial.3.gz
/usr/share/man/man3/pmLoadASCIINameSpace.3.gz
/usr/share/man/man3/pmLoadDerivedConfig.3.gz
/usr/share/man/man3/pmLoadNameSpace.3.gz
/usr/share/man/man3/pmLocaltime.3.gz
/usr/share/man/man3/pmLookupDesc.3.gz
/usr/share/man/man3/pmLookupDescs.3.gz
/usr/share/man/man3/pmLookupInDom.3.gz
/usr/share/man/man3/pmLookupInDomArchive.3.gz
/usr/share/man/man3/pmLookupInDomText.3.gz
/usr/share/man/man3/pmLookupLabels.3.gz
/usr/share/man/man3/pmLookupName.3.gz
/usr/share/man/man3/pmLookupText.3.gz
/usr/share/man/man3/pmMergeLabelSets.3.gz
/usr/share/man/man3/pmMergeLabels.3.gz
/usr/share/man/man3/pmNameAll.3.gz
/usr/share/man/man3/pmNameID.3.gz
/usr/share/man/man3/pmNameInDom.3.gz
/usr/share/man/man3/pmNameInDomArchive.3.gz
/usr/share/man/man3/pmNewContext.3.gz
/usr/share/man/man3/pmNewContextZone.3.gz
/usr/share/man/man3/pmNewZone.3.gz
/usr/share/man/man3/pmNoMem.3.gz
/usr/share/man/man3/pmNotifyErr.3.gz
/usr/share/man/man3/pmNumberStr.3.gz
/usr/share/man/man3/pmNumberStr_r.3.gz
/usr/share/man/man3/pmOpenLog.3.gz
/usr/share/man/man3/pmParseDebug.3.gz
/usr/share/man/man3/pmParseHighResInterval.3.gz
/usr/share/man/man3/pmParseHighResTimeWindow.3.gz
/usr/share/man/man3/pmParseInterval.3.gz
/usr/share/man/man3/pmParseMetricSpec.3.gz
/usr/share/man/man3/pmParseTimeWindow.3.gz
/usr/share/man/man3/pmParseUnitsStr.3.gz
/usr/share/man/man3/pmPathSeparator.3.gz
/usr/share/man/man3/pmPrintDesc.3.gz
/usr/share/man/man3/pmPrintHighResStamp.3.gz
/usr/share/man/man3/pmPrintLabelSets.3.gz
/usr/share/man/man3/pmPrintStamp.3.gz
/usr/share/man/man3/pmPrintValue.3.gz
/usr/share/man/man3/pmReconnectContext.3.gz
/usr/share/man/man3/pmRecord.3.gz
/usr/share/man/man3/pmRecordAddHost.3.gz
/usr/share/man/man3/pmRecordControl.3.gz
/usr/share/man/man3/pmRecordSetup.3.gz
/usr/share/man/man3/pmRegisterDerived.3.gz
/usr/share/man/man3/pmRegisterDerivedMetric.3.gz
/usr/share/man/man3/pmSearchClose.3.gz
/usr/share/man/man3/pmSearchInfo.3.gz
/usr/share/man/man3/pmSearchSetConfiguration.3.gz
/usr/share/man/man3/pmSearchSetEventLoop.3.gz
/usr/share/man/man3/pmSearchSetMetricRegistry.3.gz
/usr/share/man/man3/pmSearchSetSlots.3.gz
/usr/share/man/man3/pmSearchSetup.3.gz
/usr/share/man/man3/pmSearchTextInDom.3.gz
/usr/share/man/man3/pmSearchTextQuery.3.gz
/usr/share/man/man3/pmSearchTextSuggest.3.gz
/usr/share/man/man3/pmSemStr.3.gz
/usr/share/man/man3/pmSemStr_r.3.gz
/usr/share/man/man3/pmSeriesClose.3.gz
/usr/share/man/man3/pmSeriesDescs.3.gz
/usr/share/man/man3/pmSeriesInstances.3.gz
/usr/share/man/man3/pmSeriesLabelValues.3.gz
/usr/share/man/man3/pmSeriesLabels.3.gz
/usr/share/man/man3/pmSeriesLoad.3.gz
/usr/share/man/man3/pmSeriesMetrics.3.gz
/usr/share/man/man3/pmSeriesQuery.3.gz
/usr/share/man/man3/pmSeriesSetConfiguration.3.gz
/usr/share/man/man3/pmSeriesSetEventLoop.3.gz
/usr/share/man/man3/pmSeriesSetMetricRegistry.3.gz
/usr/share/man/man3/pmSeriesSetSlots.3.gz
/usr/share/man/man3/pmSeriesSetup.3.gz
/usr/share/man/man3/pmSeriesSources.3.gz
/usr/share/man/man3/pmSeriesValues.3.gz
/usr/share/man/man3/pmSeriesWindow.3.gz
/usr/share/man/man3/pmSetDebug.3.gz
/usr/share/man/man3/pmSetDerivedControl.3.gz
/usr/share/man/man3/pmSetMode.3.gz
/usr/share/man/man3/pmSetModeHighRes.3.gz
/usr/share/man/man3/pmSetProcessIdentity.3.gz
/usr/share/man/man3/pmSetProgname.3.gz
/usr/share/man/man3/pmSortHighResInstances.3.gz
/usr/share/man/man3/pmSortInstances.3.gz
/usr/share/man/man3/pmSpecLocalPMDA.3.gz
/usr/share/man/man3/pmStore.3.gz
/usr/share/man/man3/pmStoreHighRes.3.gz
/usr/share/man/man3/pmSyslog.3.gz
/usr/share/man/man3/pmTimeConnect.3.gz
/usr/share/man/man3/pmTimeDisconnect.3.gz
/usr/share/man/man3/pmTimeRecv.3.gz
/usr/share/man/man3/pmTimeSendAck.3.gz
/usr/share/man/man3/pmTimeShowDialog.3.gz
/usr/share/man/man3/pmTraversePMNS.3.gz
/usr/share/man/man3/pmTraversePMNS_r.3.gz
/usr/share/man/man3/pmTrimNameSpace.3.gz
/usr/share/man/man3/pmTypeStr.3.gz
/usr/share/man/man3/pmTypeStr_r.3.gz
/usr/share/man/man3/pmUnitsStr.3.gz
/usr/share/man/man3/pmUnitsStr_r.3.gz
/usr/share/man/man3/pmUnloadNameSpace.3.gz
/usr/share/man/man3/pmUnpackEventRecords.3.gz
/usr/share/man/man3/pmUnpackHighResEventRecords.3.gz
/usr/share/man/man3/pmUsageMessage.3.gz
/usr/share/man/man3/pmUseContext.3.gz
/usr/share/man/man3/pmUseZone.3.gz
/usr/share/man/man3/pmWebTimerRegister.3.gz
/usr/share/man/man3/pmWebTimerRelease.3.gz
/usr/share/man/man3/pmWebTimerSetMetricRegistry.3.gz
/usr/share/man/man3/pmWhichContext.3.gz
/usr/share/man/man3/pmWhichZone.3.gz
/usr/share/man/man3/pmaDeltaInDom.3.gz
/usr/share/man/man3/pmaGetLog.3.gz
/usr/share/man/man3/pmaPutLog.3.gz
/usr/share/man/man3/pmaRewriteData.3.gz
/usr/share/man/man3/pmaRewriteMeta.3.gz
/usr/share/man/man3/pmaSameInDom.3.gz
/usr/share/man/man3/pmaSortInDom.3.gz
/usr/share/man/man3/pmaTryDeltaInDom.3.gz
/usr/share/man/man3/pmaUndeltaInDom.3.gz
/usr/share/man/man3/pmdaAttribute.3.gz
/usr/share/man/man3/pmdaCache.3.gz
/usr/share/man/man3/pmdaCacheLookup.3.gz
/usr/share/man/man3/pmdaCacheLookupKey.3.gz
/usr/share/man/man3/pmdaCacheLookupName.3.gz
/usr/share/man/man3/pmdaCacheOp.3.gz
/usr/share/man/man3/pmdaCachePurge.3.gz
/usr/share/man/man3/pmdaCachePurgeCallback.3.gz
/usr/share/man/man3/pmdaCacheResize.3.gz
/usr/share/man/man3/pmdaCacheStore.3.gz
/usr/share/man/man3/pmdaCacheStoreKey.3.gz
/usr/share/man/man3/pmdaChildren.3.gz
/usr/share/man/man3/pmdaCloseHelp.3.gz
/usr/share/man/man3/pmdaConnect.3.gz
/usr/share/man/man3/pmdaDSO.3.gz
/usr/share/man/man3/pmdaDaemon.3.gz
/usr/share/man/man3/pmdaDesc.3.gz
/usr/share/man/man3/pmdaEventAddHighResMissedRecord.3.gz
/usr/share/man/man3/pmdaEventAddHighResParam.3.gz
/usr/share/man/man3/pmdaEventAddHighResRecord.3.gz
/usr/share/man/man3/pmdaEventAddMissedRecord.3.gz
/usr/share/man/man3/pmdaEventAddParam.3.gz
/usr/share/man/man3/pmdaEventAddRecord.3.gz
/usr/share/man/man3/pmdaEventArray.3.gz
/usr/share/man/man3/pmdaEventClient.3.gz
/usr/share/man/man3/pmdaEventClients.3.gz
/usr/share/man/man3/pmdaEventEndClient.3.gz
/usr/share/man/man3/pmdaEventGetAddr.3.gz
/usr/share/man/man3/pmdaEventGetHighResAddr.3.gz
/usr/share/man/man3/pmdaEventHighResAddParam.3.gz
/usr/share/man/man3/pmdaEventHighResGetAddr.3.gz
/usr/share/man/man3/pmdaEventNewActiveQueue.3.gz
/usr/share/man/man3/pmdaEventNewArray.3.gz
/usr/share/man/man3/pmdaEventNewClient.3.gz
/usr/share/man/man3/pmdaEventNewHighResArray.3.gz
/usr/share/man/man3/pmdaEventNewQueue.3.gz
/usr/share/man/man3/pmdaEventQueue.3.gz
/usr/share/man/man3/pmdaEventQueueAppend.3.gz
/usr/share/man/man3/pmdaEventQueueBytes.3.gz
/usr/share/man/man3/pmdaEventQueueClients.3.gz
/usr/share/man/man3/pmdaEventQueueCounter.3.gz
/usr/share/man/man3/pmdaEventQueueHandle.3.gz
/usr/share/man/man3/pmdaEventQueueMemory.3.gz
/usr/share/man/man3/pmdaEventQueueRecords.3.gz
/usr/share/man/man3/pmdaEventQueueShutdown.3.gz
/usr/share/man/man3/pmdaEventReleaseArray.3.gz
/usr/share/man/man3/pmdaEventReleaseHighResArray.3.gz
/usr/share/man/man3/pmdaEventResetArray.3.gz
/usr/share/man/man3/pmdaEventResetHighResArray.3.gz
/usr/share/man/man3/pmdaExtGetData.3.gz
/usr/share/man/man3/pmdaExtSetData.3.gz
/usr/share/man/man3/pmdaExtSetFlags.3.gz
/usr/share/man/man3/pmdaFetch.3.gz
/usr/share/man/man3/pmdaGetContext.3.gz
/usr/share/man/man3/pmdaGetHelp.3.gz
/usr/share/man/man3/pmdaGetInDomHelp.3.gz
/usr/share/man/man3/pmdaGetOpt.3.gz
/usr/share/man/man3/pmdaGetOptions.3.gz
/usr/share/man/man3/pmdaHelp.3.gz
/usr/share/man/man3/pmdaInit.3.gz
/usr/share/man/man3/pmdaInstance.3.gz
/usr/share/man/man3/pmdaInterfaceMoved.3.gz
/usr/share/man/man3/pmdaLabel.3.gz
/usr/share/man/man3/pmdaMain.3.gz
/usr/share/man/man3/pmdaName.3.gz
/usr/share/man/man3/pmdaOpenHelp.3.gz
/usr/share/man/man3/pmdaOpenLog.3.gz
/usr/share/man/man3/pmdaPMID.3.gz
/usr/share/man/man3/pmdaProfile.3.gz
/usr/share/man/man3/pmdaRehash.3.gz
/usr/share/man/man3/pmdaRootConnect.3.gz
/usr/share/man/man3/pmdaRootContainerCGroupName.3.gz
/usr/share/man/man3/pmdaRootContainerHostName.3.gz
/usr/share/man/man3/pmdaRootContainerProcessID.3.gz
/usr/share/man/man3/pmdaRootProcessStart.3.gz
/usr/share/man/man3/pmdaRootProcessTerminate.3.gz
/usr/share/man/man3/pmdaRootProcessWait.3.gz
/usr/share/man/man3/pmdaRootShutdown.3.gz
/usr/share/man/man3/pmdaSendError.3.gz
/usr/share/man/man3/pmdaSetCheckCallBack.3.gz
/usr/share/man/man3/pmdaSetCommFlags.3.gz
/usr/share/man/man3/pmdaSetData.3.gz
/usr/share/man/man3/pmdaSetDoneCallBack.3.gz
/usr/share/man/man3/pmdaSetEndContextCallBack.3.gz
/usr/share/man/man3/pmdaSetFetchCallBack.3.gz
/usr/share/man/man3/pmdaSetFlags.3.gz
/usr/share/man/man3/pmdaSetLabelCallBack.3.gz
/usr/share/man/man3/pmdaSetResultCallBack.3.gz
/usr/share/man/man3/pmdaStore.3.gz
/usr/share/man/man3/pmdaText.3.gz
/usr/share/man/man3/pmflush.3.gz
/usr/share/man/man3/pmfstring.3.gz
/usr/share/man/man3/pmgetopt_r.3.gz
/usr/share/man/man3/pmhttpClientFetch.3.gz
/usr/share/man/man3/pmhttpFreeClient.3.gz
/usr/share/man/man3/pmhttpNewClient.3.gz
/usr/share/man/man3/pmiAddInstance.3.gz
/usr/share/man/man3/pmiAddMetric.3.gz
/usr/share/man/man3/pmiEnd.3.gz
/usr/share/man/man3/pmiErrStr.3.gz
/usr/share/man/man3/pmiErrStr_r.3.gz
/usr/share/man/man3/pmiGetHandle.3.gz
/usr/share/man/man3/pmiID.3.gz
/usr/share/man/man3/pmiInDom.3.gz
/usr/share/man/man3/pmiPutLabel.3.gz
/usr/share/man/man3/pmiPutMark.3.gz
/usr/share/man/man3/pmiPutResult.3.gz
/usr/share/man/man3/pmiPutText.3.gz
/usr/share/man/man3/pmiPutValue.3.gz
/usr/share/man/man3/pmiPutValueHandle.3.gz
/usr/share/man/man3/pmiSetHostname.3.gz
/usr/share/man/man3/pmiSetTimezone.3.gz
/usr/share/man/man3/pmiSetVersion.3.gz
/usr/share/man/man3/pmiStart.3.gz
/usr/share/man/man3/pmiUnits.3.gz
/usr/share/man/man3/pmiUseContext.3.gz
/usr/share/man/man3/pmiWrite.3.gz
/usr/share/man/man3/pmjsonGet.3.gz
/usr/share/man/man3/pmjsonInit.3.gz
/usr/share/man/man3/pmjsonInitIndom.3.gz
/usr/share/man/man3/pmjsonPrint.3.gz
/usr/share/man/man3/pmprintf.3.gz
/usr/share/man/man3/pmsprintf.3.gz
/usr/share/man/man3/pmstrncat.3.gz
/usr/share/man/man3/pmstrncpy.3.gz
/usr/share/man/man3/pmtime.3.gz
/usr/share/man/man3/pmtimespecAdd.3.gz
/usr/share/man/man3/pmtimespecDec.3.gz
/usr/share/man/man3/pmtimespecFromReal.3.gz
/usr/share/man/man3/pmtimespecInc.3.gz
/usr/share/man/man3/pmtimespecNow.3.gz
/usr/share/man/man3/pmtimespecSub.3.gz
/usr/share/man/man3/pmtimespecToReal.3.gz
/usr/share/man/man3/pmtimevalAdd.3.gz
/usr/share/man/man3/pmtimevalDec.3.gz
/usr/share/man/man3/pmtimevalFromReal.3.gz
/usr/share/man/man3/pmtimevalInc.3.gz
/usr/share/man/man3/pmtimevalNow.3.gz
/usr/share/man/man3/pmtimevalSub.3.gz
/usr/share/man/man3/pmtimevalToReal.3.gz
/usr/share/man/man3/pmtrace.3.gz
/usr/share/man/man3/pmtraceabort.3.gz
/usr/share/man/man3/pmtracebegin.3.gz
/usr/share/man/man3/pmtracecounter.3.gz
/usr/share/man/man3/pmtraceend.3.gz
/usr/share/man/man3/pmtraceerrstr.3.gz
/usr/share/man/man3/pmtraceobs.3.gz
/usr/share/man/man3/pmtracepoint.3.gz
/usr/share/man/man3/pmtracestate.3.gz
/usr/share/man/man3/zbxpcp.3.gz

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/pcp-doc/html/diskmodel/model.fio
/usr/share/doc/pcp-doc/html/diskmodel/model.folio
/usr/share/doc/pcp-doc/html/diskmodel/model.pl
/usr/share/doc/pcp-doc/html/diskmodel/model.view
/usr/share/doc/pcp-doc/html/diskmodel/model.xls
/usr/share/doc/pcp-doc/html/diskmodel/nasread.out
/usr/share/doc/pcp-doc/html/diskmodel/naswrite.out
/usr/share/doc/pcp-doc/html/guide.html
/usr/share/doc/pcp-doc/html/howto.cpuperf.html
/usr/share/doc/pcp-doc/html/howto.diskmodel.html
/usr/share/doc/pcp-doc/html/howto.diskperf.html
/usr/share/doc/pcp-doc/html/howto.enterprise.html
/usr/share/doc/pcp-doc/html/howto.systemlog.html
/usr/share/doc/pcp-doc/html/images/cpu_pswitch.png
/usr/share/doc/pcp-doc/html/images/dkvis.png
/usr/share/doc/pcp-doc/html/images/elasticsearch.png
/usr/share/doc/pcp-doc/html/images/linux-cpu.png
/usr/share/doc/pcp-doc/html/images/linux-virt-cpu.png
/usr/share/doc/pcp-doc/html/images/model_biload.png
/usr/share/doc/pcp-doc/html/images/model_dbload.png
/usr/share/doc/pcp-doc/html/images/model_nasload.png
/usr/share/doc/pcp-doc/html/images/model_spreadsheet.png
/usr/share/doc/pcp-doc/html/images/mover.nfile.counter.3min.png
/usr/share/doc/pcp-doc/html/images/mover.nfile.counter.png
/usr/share/doc/pcp-doc/html/images/mover.nfile.instant.3min.png
/usr/share/doc/pcp-doc/html/images/mover.nfile.instant.png
/usr/share/doc/pcp-doc/html/images/mover.nfile.step.png
/usr/share/doc/pcp-doc/html/images/mover.png
/usr/share/doc/pcp-doc/html/images/mover.v3.png
/usr/share/doc/pcp-doc/html/images/mpvis.png
/usr/share/doc/pcp-doc/html/images/ovevents.png
/usr/share/doc/pcp-doc/html/images/pcp.ico
/usr/share/doc/pcp-doc/html/images/pcpicon-light.png
/usr/share/doc/pcp-doc/html/images/pcpicon.png
/usr/share/doc/pcp-doc/html/images/pmchart_add_host_container.png
/usr/share/doc/pcp-doc/html/images/pmchart_add_host_secure.png
/usr/share/doc/pcp-doc/html/images/pmchart_blank_canvas.png
/usr/share/doc/pcp-doc/html/images/pmchart_cpu_disk.png
/usr/share/doc/pcp-doc/html/images/pmchart_cpu_disk_load.png
/usr/share/doc/pcp-doc/html/images/pmchart_cpu_disk_record.png
/usr/share/doc/pcp-doc/html/images/pmchart_edit_chart.png
/usr/share/doc/pcp-doc/html/images/pmchart_new_chart.png
/usr/share/doc/pcp-doc/html/images/pmchart_new_chart_colors.png
/usr/share/doc/pcp-doc/html/images/pmchart_new_chart_select.png
/usr/share/doc/pcp-doc/html/images/pmchart_open_view.png
/usr/share/doc/pcp-doc/html/images/pmchart_stop_recording.png
/usr/share/doc/pcp-doc/html/images/pmcharticon.png
/usr/share/doc/pcp-doc/html/images/pmie_axis1.png
/usr/share/doc/pcp-doc/html/images/pmie_axis2.png
/usr/share/doc/pcp-doc/html/images/pmie_axis3.png
/usr/share/doc/pcp-doc/html/images/pmie_axis4.png
/usr/share/doc/pcp-doc/html/images/pmie_rule1.png
/usr/share/doc/pcp-doc/html/images/pmie_rule2.png
/usr/share/doc/pcp-doc/html/images/pmie_rule3.png
/usr/share/doc/pcp-doc/html/images/pmie_rule4.png
/usr/share/doc/pcp-doc/html/images/pmie_rule5.png
/usr/share/doc/pcp-doc/html/images/pmie_rule6.png
/usr/share/doc/pcp-doc/html/images/pmtime_archive.png
/usr/share/doc/pcp-doc/html/images/pmtime_bounds.png
/usr/share/doc/pcp-doc/html/images/pmtime_clients.png
/usr/share/doc/pcp-doc/html/images/pmtime_live.png
/usr/share/doc/pcp-doc/html/images/pmtimeicon.png
/usr/share/doc/pcp-doc/html/images/pmview.flow.png
/usr/share/doc/pcp-doc/html/images/pmview_buttons.png
/usr/share/doc/pcp-doc/html/images/rattle.png
/usr/share/doc/pcp-doc/html/images/sar-d.png
/usr/share/doc/pcp-doc/html/images/stepfwd_on.png
/usr/share/doc/pcp-doc/html/images/system-search.png
/usr/share/doc/pcp-doc/html/images/systemlog-arrival.png
/usr/share/doc/pcp-doc/html/images/systemlog-events.png
/usr/share/doc/pcp-doc/html/images/systemlog-throughput.png
/usr/share/doc/pcp-doc/html/images/systemlogs.png
/usr/share/doc/pcp-doc/html/images/tngconsole.png
/usr/share/doc/pcp-doc/html/images/trace_1.png
/usr/share/doc/pcp-doc/html/images/trace_buffer.png
/usr/share/doc/pcp-doc/html/images/trace_example.png
/usr/share/doc/pcp-doc/html/images/trace_libpcp.png
/usr/share/doc/pcp-doc/html/images/vector-containers.png
/usr/share/doc/pcp-doc/html/images/xenln.png
/usr/share/doc/pcp-doc/html/images/xnmevents.png
/usr/share/doc/pcp-doc/html/importdata/mover2pcp
/usr/share/doc/pcp-doc/html/index.html
/usr/share/doc/pcp-doc/html/installation.html
/usr/share/doc/pcp-doc/html/lab.auth.html
/usr/share/doc/pcp-doc/html/lab.containers.html
/usr/share/doc/pcp-doc/html/lab.importdata.html
/usr/share/doc/pcp-doc/html/lab.pmchart.html
/usr/share/doc/pcp-doc/html/lab.pmie.html
/usr/share/doc/pcp-doc/html/lab.pmieconf.html
/usr/share/doc/pcp-doc/html/lab.pmlogger.html
/usr/share/doc/pcp-doc/html/lab.pmview.html
/usr/share/doc/pcp-doc/html/lab.secure.html
/usr/share/doc/pcp-doc/html/lab.secureclient.html
/usr/share/doc/pcp-doc/html/overview.html
/usr/share/doc/pcp-doc/html/pcpdoc.css
/usr/share/doc/pcp-doc/html/pmchart.html
/usr/share/doc/pcp-doc/html/pmie/answer.pmie
/usr/share/doc/pcp-doc/html/pmie/disk.pmie
/usr/share/doc/pcp-doc/html/pmie/pswitch.pmie
/usr/share/doc/pcp-doc/html/pmie/pswitch.view
/usr/share/doc/pcp-doc/html/pmview/example.view
/usr/share/doc/pcp-doc/html/pmview/godzilla.web.folio
/usr/share/doc/pcp-doc/html/pmview/godzilla.web.view
/usr/share/doc/pcp-doc/html/portability-and-qa.html
/usr/share/doc/pcp-doc/html/timecontrol.html
/usr/share/doc/pcp-doc/html/views.html
/usr/share/doc/pcp/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpcp.so.3
/usr/lib64/libpcp_archive.so.1
/usr/lib64/libpcp_fault.so.3
/usr/lib64/libpcp_gui.so.2
/usr/lib64/libpcp_import.so.1
/usr/lib64/libpcp_mmv.so.1
/usr/lib64/libpcp_pmda.so.3
/usr/lib64/libpcp_trace.so.2
/usr/lib64/libpcp_web.so.1
/usr/lib64/zabbix/agent/zbxpcp.so
/usr/lib64/zabbix/modules/zbxpcp.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/pcp/bin/chkhelp
/usr/libexec/pcp/bin/discover/pcp-kube-pods
/usr/libexec/pcp/bin/find-filter
/usr/libexec/pcp/bin/install-sh
/usr/libexec/pcp/bin/mkaf
/usr/libexec/pcp/bin/newhelp
/usr/libexec/pcp/bin/pcp-atop
/usr/libexec/pcp/bin/pcp-atopsar
/usr/libexec/pcp/bin/pcp-dmcache
/usr/libexec/pcp/bin/pcp-dstat
/usr/libexec/pcp/bin/pcp-free
/usr/libexec/pcp/bin/pcp-htop
/usr/libexec/pcp/bin/pcp-iostat
/usr/libexec/pcp/bin/pcp-ipcs
/usr/libexec/pcp/bin/pcp-lvmcache
/usr/libexec/pcp/bin/pcp-mpstat
/usr/libexec/pcp/bin/pcp-numastat
/usr/libexec/pcp/bin/pcp-pidstat
/usr/libexec/pcp/bin/pcp-ps
/usr/libexec/pcp/bin/pcp-python
/usr/libexec/pcp/bin/pcp-shping
/usr/libexec/pcp/bin/pcp-ss
/usr/libexec/pcp/bin/pcp-summary
/usr/libexec/pcp/bin/pcp-tapestat
/usr/libexec/pcp/bin/pcp-uptime
/usr/libexec/pcp/bin/pcp-verify
/usr/libexec/pcp/bin/pcp-vmstat
/usr/libexec/pcp/bin/pmcd
/usr/libexec/pcp/bin/pmcd_wait
/usr/libexec/pcp/bin/pmconfig
/usr/libexec/pcp/bin/pmcpp
/usr/libexec/pcp/bin/pmfind_check
/usr/libexec/pcp/bin/pmgetopt
/usr/libexec/pcp/bin/pmhostname
/usr/libexec/pcp/bin/pmie_check
/usr/libexec/pcp/bin/pmie_daily
/usr/libexec/pcp/bin/pmie_dump_stats
/usr/libexec/pcp/bin/pmie_email
/usr/libexec/pcp/bin/pmie_farm
/usr/libexec/pcp/bin/pmie_webhook
/usr/libexec/pcp/bin/pmiestatus
/usr/libexec/pcp/bin/pmlock
/usr/libexec/pcp/bin/pmlogconf
/usr/libexec/pcp/bin/pmlogextract
/usr/libexec/pcp/bin/pmlogger
/usr/libexec/pcp/bin/pmlogger_check
/usr/libexec/pcp/bin/pmlogger_daily
/usr/libexec/pcp/bin/pmlogger_daily_report
/usr/libexec/pcp/bin/pmlogger_farm
/usr/libexec/pcp/bin/pmlogger_janitor
/usr/libexec/pcp/bin/pmlogger_merge
/usr/libexec/pcp/bin/pmlogger_rewrite
/usr/libexec/pcp/bin/pmlogreduce
/usr/libexec/pcp/bin/pmlogrewrite
/usr/libexec/pcp/bin/pmnewlog
/usr/libexec/pcp/bin/pmnsadd
/usr/libexec/pcp/bin/pmnsdel
/usr/libexec/pcp/bin/pmnsmerge
/usr/libexec/pcp/bin/pmpause
/usr/libexec/pcp/bin/pmpost
/usr/libexec/pcp/bin/pmproxy
/usr/libexec/pcp/bin/pmsignal
/usr/libexec/pcp/bin/pmsleep
/usr/libexec/pcp/bin/pmsnap
/usr/libexec/pcp/bin/pmwtf
/usr/libexec/pcp/bin/telnet-probe
/usr/libexec/pcp/lib/bashproc.sh
/usr/libexec/pcp/lib/pcp
/usr/libexec/pcp/lib/pmcd
/usr/libexec/pcp/lib/pmdaproc.sh
/usr/libexec/pcp/lib/pmie
/usr/libexec/pcp/lib/pmlogger
/usr/libexec/pcp/lib/pmproxy
/usr/libexec/pcp/lib/rc-proc.sh
/usr/libexec/pcp/lib/rc-proc.sh.minimal
/usr/libexec/pcp/lib/utilproc.sh
/usr/libexec/pcp/pmdas/apache/Install
/usr/libexec/pcp/pmdas/apache/README
/usr/libexec/pcp/pmdas/apache/Remove
/usr/libexec/pcp/pmdas/apache/domain.h
/usr/libexec/pcp/pmdas/apache/help
/usr/libexec/pcp/pmdas/apache/pmdaapache
/usr/libexec/pcp/pmdas/apache/pmns
/usr/libexec/pcp/pmdas/apache/root
/usr/libexec/pcp/pmdas/bash/Install
/usr/libexec/pcp/pmdas/bash/Remove
/usr/libexec/pcp/pmdas/bash/domain.h
/usr/libexec/pcp/pmdas/bash/help
/usr/libexec/pcp/pmdas/bash/pmdabash
/usr/libexec/pcp/pmdas/bash/pmns
/usr/libexec/pcp/pmdas/bash/root
/usr/libexec/pcp/pmdas/bash/test-child.sh
/usr/libexec/pcp/pmdas/bash/test-trace.sh
/usr/libexec/pcp/pmdas/bonding/Install
/usr/libexec/pcp/pmdas/bonding/Remove
/usr/libexec/pcp/pmdas/bonding/pmdabonding.pl
/usr/libexec/pcp/pmdas/cifs/Install
/usr/libexec/pcp/pmdas/cifs/Remove
/usr/libexec/pcp/pmdas/cifs/domain.h
/usr/libexec/pcp/pmdas/cifs/help
/usr/libexec/pcp/pmdas/cifs/pmda_cifs.so
/usr/libexec/pcp/pmdas/cifs/pmdacifs
/usr/libexec/pcp/pmdas/cifs/pmns
/usr/libexec/pcp/pmdas/cifs/root
/usr/libexec/pcp/pmdas/cisco/Install
/usr/libexec/pcp/pmdas/cisco/README
/usr/libexec/pcp/pmdas/cisco/Remove
/usr/libexec/pcp/pmdas/cisco/domain.h
/usr/libexec/pcp/pmdas/cisco/help
/usr/libexec/pcp/pmdas/cisco/parse
/usr/libexec/pcp/pmdas/cisco/pmdacisco
/usr/libexec/pcp/pmdas/cisco/pmns
/usr/libexec/pcp/pmdas/cisco/probe
/usr/libexec/pcp/pmdas/cisco/root
/usr/libexec/pcp/pmdas/dbping/Install
/usr/libexec/pcp/pmdas/dbping/Remove
/usr/libexec/pcp/pmdas/dbping/dbprobe.pl
/usr/libexec/pcp/pmdas/dbping/pmdadbping.pl
/usr/libexec/pcp/pmdas/denki/Install
/usr/libexec/pcp/pmdas/denki/README
/usr/libexec/pcp/pmdas/denki/Remove
/usr/libexec/pcp/pmdas/denki/domain.h
/usr/libexec/pcp/pmdas/denki/help
/usr/libexec/pcp/pmdas/denki/help.dir
/usr/libexec/pcp/pmdas/denki/help.pag
/usr/libexec/pcp/pmdas/denki/pmda_denki.so
/usr/libexec/pcp/pmdas/denki/pmdadenki
/usr/libexec/pcp/pmdas/denki/root
/usr/libexec/pcp/pmdas/denki/root_denki
/usr/libexec/pcp/pmdas/dm/Install
/usr/libexec/pcp/pmdas/dm/Remove
/usr/libexec/pcp/pmdas/dm/Upgrade
/usr/libexec/pcp/pmdas/dm/domain.h
/usr/libexec/pcp/pmdas/dm/help
/usr/libexec/pcp/pmdas/dm/pmda_dm.so
/usr/libexec/pcp/pmdas/dm/pmdadm
/usr/libexec/pcp/pmdas/dm/pmns.dmcache
/usr/libexec/pcp/pmdas/dm/pmns.dmstats
/usr/libexec/pcp/pmdas/dm/pmns.dmthin
/usr/libexec/pcp/pmdas/dm/pmns.vdo
/usr/libexec/pcp/pmdas/dm/root
/usr/libexec/pcp/pmdas/docker/Install
/usr/libexec/pcp/pmdas/docker/Remove
/usr/libexec/pcp/pmdas/docker/domain.h
/usr/libexec/pcp/pmdas/docker/help
/usr/libexec/pcp/pmdas/docker/pmda_docker.so
/usr/libexec/pcp/pmdas/docker/pmdadocker
/usr/libexec/pcp/pmdas/docker/pmns
/usr/libexec/pcp/pmdas/docker/root
/usr/libexec/pcp/pmdas/ds389/Install
/usr/libexec/pcp/pmdas/ds389/Remove
/usr/libexec/pcp/pmdas/ds389/ds389.conf.example
/usr/libexec/pcp/pmdas/ds389/pmdads389.pl
/usr/libexec/pcp/pmdas/ds389log/Install
/usr/libexec/pcp/pmdas/ds389log/Remove
/usr/libexec/pcp/pmdas/ds389log/pmdads389log.pl
/usr/libexec/pcp/pmdas/elasticsearch/Install
/usr/libexec/pcp/pmdas/elasticsearch/Remove
/usr/libexec/pcp/pmdas/elasticsearch/Upgrade
/usr/libexec/pcp/pmdas/elasticsearch/pmdaelasticsearch.python
/usr/libexec/pcp/pmdas/gfs2/Install
/usr/libexec/pcp/pmdas/gfs2/Remove
/usr/libexec/pcp/pmdas/gfs2/domain.h
/usr/libexec/pcp/pmdas/gfs2/help
/usr/libexec/pcp/pmdas/gfs2/pmdagfs2
/usr/libexec/pcp/pmdas/gfs2/pmns
/usr/libexec/pcp/pmdas/gfs2/root
/usr/libexec/pcp/pmdas/gluster/Install
/usr/libexec/pcp/pmdas/gluster/Remove
/usr/libexec/pcp/pmdas/gluster/pmdagluster.python
/usr/libexec/pcp/pmdas/gpfs/Install
/usr/libexec/pcp/pmdas/gpfs/Remove
/usr/libexec/pcp/pmdas/gpfs/pmdagpfs.pl
/usr/libexec/pcp/pmdas/gpsd/Install
/usr/libexec/pcp/pmdas/gpsd/Remove
/usr/libexec/pcp/pmdas/gpsd/pmdagpsd.pl
/usr/libexec/pcp/pmdas/hacluster/Install
/usr/libexec/pcp/pmdas/hacluster/Remove
/usr/libexec/pcp/pmdas/hacluster/domain.h
/usr/libexec/pcp/pmdas/hacluster/help
/usr/libexec/pcp/pmdas/hacluster/pmda_hacluster.so
/usr/libexec/pcp/pmdas/hacluster/pmdahacluster
/usr/libexec/pcp/pmdas/hacluster/pmns
/usr/libexec/pcp/pmdas/hacluster/root
/usr/libexec/pcp/pmdas/haproxy/Install
/usr/libexec/pcp/pmdas/haproxy/Remove
/usr/libexec/pcp/pmdas/haproxy/connect
/usr/libexec/pcp/pmdas/haproxy/pmdahaproxy.python
/usr/libexec/pcp/pmdas/jbd2/Install
/usr/libexec/pcp/pmdas/jbd2/Remove
/usr/libexec/pcp/pmdas/jbd2/domain.h
/usr/libexec/pcp/pmdas/jbd2/help
/usr/libexec/pcp/pmdas/jbd2/help.dir
/usr/libexec/pcp/pmdas/jbd2/help.pag
/usr/libexec/pcp/pmdas/jbd2/pmda_jbd2.so
/usr/libexec/pcp/pmdas/jbd2/pmdajbd2
/usr/libexec/pcp/pmdas/jbd2/root
/usr/libexec/pcp/pmdas/jbd2/root_jbd2
/usr/libexec/pcp/pmdas/kvm/Install
/usr/libexec/pcp/pmdas/kvm/Remove
/usr/libexec/pcp/pmdas/kvm/Upgrade
/usr/libexec/pcp/pmdas/kvm/domain.h
/usr/libexec/pcp/pmdas/kvm/help
/usr/libexec/pcp/pmdas/kvm/help.dir
/usr/libexec/pcp/pmdas/kvm/help.pag
/usr/libexec/pcp/pmdas/kvm/pmda_kvm.so
/usr/libexec/pcp/pmdas/kvm/pmdakvm
/usr/libexec/pcp/pmdas/kvm/root
/usr/libexec/pcp/pmdas/kvm/root_kvm
/usr/libexec/pcp/pmdas/linux/domain.h
/usr/libexec/pcp/pmdas/linux/help
/usr/libexec/pcp/pmdas/linux/help.dir
/usr/libexec/pcp/pmdas/linux/help.pag
/usr/libexec/pcp/pmdas/linux/pmda_linux.so
/usr/libexec/pcp/pmdas/linux/pmdalinux
/usr/libexec/pcp/pmdas/lmsensors/Install
/usr/libexec/pcp/pmdas/lmsensors/README
/usr/libexec/pcp/pmdas/lmsensors/Remove
/usr/libexec/pcp/pmdas/lmsensors/help
/usr/libexec/pcp/pmdas/lmsensors/pmdalmsensors.python
/usr/libexec/pcp/pmdas/lmsensors/pmns
/usr/libexec/pcp/pmdas/lmsensors/root
/usr/libexec/pcp/pmdas/logger/Install
/usr/libexec/pcp/pmdas/logger/README
/usr/libexec/pcp/pmdas/logger/Remove
/usr/libexec/pcp/pmdas/logger/domain.h
/usr/libexec/pcp/pmdas/logger/help
/usr/libexec/pcp/pmdas/logger/pmdalogger
/usr/libexec/pcp/pmdas/logger/pmns
/usr/libexec/pcp/pmdas/logger/root
/usr/libexec/pcp/pmdas/lustre/Install
/usr/libexec/pcp/pmdas/lustre/Remove
/usr/libexec/pcp/pmdas/lustre/pmdalustre.pl
/usr/libexec/pcp/pmdas/lustrecomm/Install
/usr/libexec/pcp/pmdas/lustrecomm/README
/usr/libexec/pcp/pmdas/lustrecomm/Remove
/usr/libexec/pcp/pmdas/lustrecomm/domain.h
/usr/libexec/pcp/pmdas/lustrecomm/help
/usr/libexec/pcp/pmdas/lustrecomm/pmdalustrecomm
/usr/libexec/pcp/pmdas/lustrecomm/pmns
/usr/libexec/pcp/pmdas/lustrecomm/root
/usr/libexec/pcp/pmdas/mailq/Install
/usr/libexec/pcp/pmdas/mailq/README
/usr/libexec/pcp/pmdas/mailq/Remove
/usr/libexec/pcp/pmdas/mailq/domain.h
/usr/libexec/pcp/pmdas/mailq/help
/usr/libexec/pcp/pmdas/mailq/pmdamailq
/usr/libexec/pcp/pmdas/mailq/pmns
/usr/libexec/pcp/pmdas/mailq/root
/usr/libexec/pcp/pmdas/memcache/Install
/usr/libexec/pcp/pmdas/memcache/Remove
/usr/libexec/pcp/pmdas/memcache/pmdamemcache.pl
/usr/libexec/pcp/pmdas/mic/Install
/usr/libexec/pcp/pmdas/mic/Remove
/usr/libexec/pcp/pmdas/mic/pmdamic.python
/usr/libexec/pcp/pmdas/mmv/Install
/usr/libexec/pcp/pmdas/mmv/Remove
/usr/libexec/pcp/pmdas/mmv/domain.h
/usr/libexec/pcp/pmdas/mmv/mmvdump
/usr/libexec/pcp/pmdas/mmv/pmda_mmv.so
/usr/libexec/pcp/pmdas/mmv/pmdammv
/usr/libexec/pcp/pmdas/mmv/root_mmv
/usr/libexec/pcp/pmdas/mounts/Install
/usr/libexec/pcp/pmdas/mounts/README
/usr/libexec/pcp/pmdas/mounts/Remove
/usr/libexec/pcp/pmdas/mounts/domain.h
/usr/libexec/pcp/pmdas/mounts/help
/usr/libexec/pcp/pmdas/mounts/pmdamounts
/usr/libexec/pcp/pmdas/mounts/pmns
/usr/libexec/pcp/pmdas/mounts/root
/usr/libexec/pcp/pmdas/mssql/Install
/usr/libexec/pcp/pmdas/mssql/Remove
/usr/libexec/pcp/pmdas/mssql/Upgrade
/usr/libexec/pcp/pmdas/mssql/pmdamssql.python
/usr/libexec/pcp/pmdas/named/Install
/usr/libexec/pcp/pmdas/named/Remove
/usr/libexec/pcp/pmdas/named/pmdanamed.pl
/usr/libexec/pcp/pmdas/netcheck/Install
/usr/libexec/pcp/pmdas/netcheck/Remove
/usr/libexec/pcp/pmdas/netcheck/modules/__init__.python
/usr/libexec/pcp/pmdas/netcheck/modules/dns_lookup.python
/usr/libexec/pcp/pmdas/netcheck/modules/dns_reverse.python
/usr/libexec/pcp/pmdas/netcheck/modules/pcpnetcheck.python
/usr/libexec/pcp/pmdas/netcheck/modules/ping.python
/usr/libexec/pcp/pmdas/netcheck/modules/ping_latency.python
/usr/libexec/pcp/pmdas/netcheck/modules/ping_loss.python
/usr/libexec/pcp/pmdas/netcheck/modules/port_open.python
/usr/libexec/pcp/pmdas/netcheck/modules/url_get.python
/usr/libexec/pcp/pmdas/netcheck/pmdanetcheck.python
/usr/libexec/pcp/pmdas/netcheck/pmdautil.python
/usr/libexec/pcp/pmdas/netcheck/pyprep
/usr/libexec/pcp/pmdas/netfilter/Install
/usr/libexec/pcp/pmdas/netfilter/Remove
/usr/libexec/pcp/pmdas/netfilter/pmdanetfilter.pl
/usr/libexec/pcp/pmdas/news/Install
/usr/libexec/pcp/pmdas/news/README
/usr/libexec/pcp/pmdas/news/Remove
/usr/libexec/pcp/pmdas/news/active
/usr/libexec/pcp/pmdas/news/pmdanews.pl
/usr/libexec/pcp/pmdas/nfsclient/Install
/usr/libexec/pcp/pmdas/nfsclient/Remove
/usr/libexec/pcp/pmdas/nfsclient/Upgrade
/usr/libexec/pcp/pmdas/nfsclient/pmdanfsclient.python
/usr/libexec/pcp/pmdas/nvidia/Install
/usr/libexec/pcp/pmdas/nvidia/README
/usr/libexec/pcp/pmdas/nvidia/Remove
/usr/libexec/pcp/pmdas/nvidia/domain.h
/usr/libexec/pcp/pmdas/nvidia/help
/usr/libexec/pcp/pmdas/nvidia/pmda_nvidia.so
/usr/libexec/pcp/pmdas/nvidia/pmdanvidia
/usr/libexec/pcp/pmdas/nvidia/pmns
/usr/libexec/pcp/pmdas/nvidia/root
/usr/libexec/pcp/pmdas/openvswitch/Install
/usr/libexec/pcp/pmdas/openvswitch/Remove
/usr/libexec/pcp/pmdas/openvswitch/pmdaopenvswitch.python
/usr/libexec/pcp/pmdas/overhead/Install
/usr/libexec/pcp/pmdas/overhead/README
/usr/libexec/pcp/pmdas/overhead/Remove
/usr/libexec/pcp/pmdas/overhead/domain.h
/usr/libexec/pcp/pmdas/overhead/pmdaoverhead
/usr/libexec/pcp/pmdas/overhead/pmns
/usr/libexec/pcp/pmdas/overhead/root
/usr/libexec/pcp/pmdas/pdns/Install
/usr/libexec/pcp/pmdas/pdns/Remove
/usr/libexec/pcp/pmdas/pdns/pmdapdns.pl
/usr/libexec/pcp/pmdas/pipe/Install
/usr/libexec/pcp/pmdas/pipe/README
/usr/libexec/pcp/pmdas/pipe/Remove
/usr/libexec/pcp/pmdas/pipe/domain.h
/usr/libexec/pcp/pmdas/pipe/help
/usr/libexec/pcp/pmdas/pipe/pmdapipe
/usr/libexec/pcp/pmdas/pipe/pmns
/usr/libexec/pcp/pmdas/pipe/root
/usr/libexec/pcp/pmdas/pmcd/help.dir
/usr/libexec/pcp/pmdas/pmcd/help.pag
/usr/libexec/pcp/pmdas/pmcd/pmda_pmcd.so
/usr/libexec/pcp/pmdas/podman/Install
/usr/libexec/pcp/pmdas/podman/Remove
/usr/libexec/pcp/pmdas/podman/domain.h
/usr/libexec/pcp/pmdas/podman/help
/usr/libexec/pcp/pmdas/podman/help.dir
/usr/libexec/pcp/pmdas/podman/help.pag
/usr/libexec/pcp/pmdas/podman/pmda_podman.so
/usr/libexec/pcp/pmdas/podman/pmdapodman
/usr/libexec/pcp/pmdas/podman/root
/usr/libexec/pcp/pmdas/podman/root_podman
/usr/libexec/pcp/pmdas/proc/Install
/usr/libexec/pcp/pmdas/proc/Remove
/usr/libexec/pcp/pmdas/proc/domain.h
/usr/libexec/pcp/pmdas/proc/help
/usr/libexec/pcp/pmdas/proc/help.dir
/usr/libexec/pcp/pmdas/proc/help.pag
/usr/libexec/pcp/pmdas/proc/pmda_proc.so
/usr/libexec/pcp/pmdas/proc/pmdaproc
/usr/libexec/pcp/pmdas/proc/root
/usr/libexec/pcp/pmdas/proc/root_proc
/usr/libexec/pcp/pmdas/rabbitmq/Install
/usr/libexec/pcp/pmdas/rabbitmq/Remove
/usr/libexec/pcp/pmdas/rabbitmq/pmdarabbitmq.python
/usr/libexec/pcp/pmdas/redis/Install
/usr/libexec/pcp/pmdas/redis/Remove
/usr/libexec/pcp/pmdas/redis/pmdaredis.pl
/usr/libexec/pcp/pmdas/roomtemp/Install
/usr/libexec/pcp/pmdas/roomtemp/README
/usr/libexec/pcp/pmdas/roomtemp/Remove
/usr/libexec/pcp/pmdas/roomtemp/domain.h
/usr/libexec/pcp/pmdas/roomtemp/help
/usr/libexec/pcp/pmdas/roomtemp/pmdaroomtemp
/usr/libexec/pcp/pmdas/roomtemp/pmns
/usr/libexec/pcp/pmdas/roomtemp/root
/usr/libexec/pcp/pmdas/root/domain.h
/usr/libexec/pcp/pmdas/root/help
/usr/libexec/pcp/pmdas/root/help.dir
/usr/libexec/pcp/pmdas/root/help.pag
/usr/libexec/pcp/pmdas/root/pmdaroot
/usr/libexec/pcp/pmdas/root/root
/usr/libexec/pcp/pmdas/root/root_root
/usr/libexec/pcp/pmdas/rsyslog/Install
/usr/libexec/pcp/pmdas/rsyslog/Remove
/usr/libexec/pcp/pmdas/rsyslog/pmdarsyslog.pl
/usr/libexec/pcp/pmdas/samba/Install
/usr/libexec/pcp/pmdas/samba/Remove
/usr/libexec/pcp/pmdas/samba/pmdasamba.pl
/usr/libexec/pcp/pmdas/sample/Install
/usr/libexec/pcp/pmdas/sample/Makefile
/usr/libexec/pcp/pmdas/sample/README
/usr/libexec/pcp/pmdas/sample/Remove
/usr/libexec/pcp/pmdas/sample/domain.h
/usr/libexec/pcp/pmdas/sample/events.c
/usr/libexec/pcp/pmdas/sample/events.h
/usr/libexec/pcp/pmdas/sample/help
/usr/libexec/pcp/pmdas/sample/libpcp.h
/usr/libexec/pcp/pmdas/sample/percontext.c
/usr/libexec/pcp/pmdas/sample/percontext.h
/usr/libexec/pcp/pmdas/sample/pmda.c
/usr/libexec/pcp/pmdas/sample/pmda_sample.so
/usr/libexec/pcp/pmdas/sample/pmdasample
/usr/libexec/pcp/pmdas/sample/pmns
/usr/libexec/pcp/pmdas/sample/proc.c
/usr/libexec/pcp/pmdas/sample/proc.h
/usr/libexec/pcp/pmdas/sample/root
/usr/libexec/pcp/pmdas/sample/sample.c
/usr/libexec/pcp/pmdas/sendmail/Install
/usr/libexec/pcp/pmdas/sendmail/README
/usr/libexec/pcp/pmdas/sendmail/Remove
/usr/libexec/pcp/pmdas/sendmail/domain.h
/usr/libexec/pcp/pmdas/sendmail/help
/usr/libexec/pcp/pmdas/sendmail/pmda_sendmail.so
/usr/libexec/pcp/pmdas/sendmail/pmdasendmail
/usr/libexec/pcp/pmdas/sendmail/pmns
/usr/libexec/pcp/pmdas/sendmail/root
/usr/libexec/pcp/pmdas/shping/Install
/usr/libexec/pcp/pmdas/shping/README
/usr/libexec/pcp/pmdas/shping/Remove
/usr/libexec/pcp/pmdas/shping/domain.h
/usr/libexec/pcp/pmdas/shping/help
/usr/libexec/pcp/pmdas/shping/pmdashping
/usr/libexec/pcp/pmdas/shping/pmns
/usr/libexec/pcp/pmdas/shping/root
/usr/libexec/pcp/pmdas/simple/Install
/usr/libexec/pcp/pmdas/simple/Makefile
/usr/libexec/pcp/pmdas/simple/README
/usr/libexec/pcp/pmdas/simple/Remove
/usr/libexec/pcp/pmdas/simple/domain.h
/usr/libexec/pcp/pmdas/simple/help
/usr/libexec/pcp/pmdas/simple/pmdasimple.perl
/usr/libexec/pcp/pmdas/simple/pmdasimple.python
/usr/libexec/pcp/pmdas/simple/pmns
/usr/libexec/pcp/pmdas/simple/root
/usr/libexec/pcp/pmdas/simple/simple.c
/usr/libexec/pcp/pmdas/slurm/Install
/usr/libexec/pcp/pmdas/slurm/Remove
/usr/libexec/pcp/pmdas/slurm/pmdaslurm.pl
/usr/libexec/pcp/pmdas/smart/Install
/usr/libexec/pcp/pmdas/smart/Remove
/usr/libexec/pcp/pmdas/smart/domain.h
/usr/libexec/pcp/pmdas/smart/help
/usr/libexec/pcp/pmdas/smart/pmda_smart.so
/usr/libexec/pcp/pmdas/smart/pmdasmart
/usr/libexec/pcp/pmdas/smart/pmns
/usr/libexec/pcp/pmdas/smart/root
/usr/libexec/pcp/pmdas/sockets/Install
/usr/libexec/pcp/pmdas/sockets/Remove
/usr/libexec/pcp/pmdas/sockets/Upgrade
/usr/libexec/pcp/pmdas/sockets/domain.h
/usr/libexec/pcp/pmdas/sockets/help
/usr/libexec/pcp/pmdas/sockets/pmda_sockets.so
/usr/libexec/pcp/pmdas/sockets/pmdasockets
/usr/libexec/pcp/pmdas/sockets/pmns
/usr/libexec/pcp/pmdas/sockets/root
/usr/libexec/pcp/pmdas/summary/Install
/usr/libexec/pcp/pmdas/summary/README
/usr/libexec/pcp/pmdas/summary/Remove
/usr/libexec/pcp/pmdas/summary/domain.h
/usr/libexec/pcp/pmdas/summary/help
/usr/libexec/pcp/pmdas/summary/pmdasummary
/usr/libexec/pcp/pmdas/summary/pmns
/usr/libexec/pcp/pmdas/summary/root
/usr/libexec/pcp/pmdas/systemd/Install
/usr/libexec/pcp/pmdas/systemd/README
/usr/libexec/pcp/pmdas/systemd/Remove
/usr/libexec/pcp/pmdas/systemd/domain.h
/usr/libexec/pcp/pmdas/systemd/help
/usr/libexec/pcp/pmdas/systemd/pmdasystemd
/usr/libexec/pcp/pmdas/systemd/pmns
/usr/libexec/pcp/pmdas/systemd/root
/usr/libexec/pcp/pmdas/trace/Install
/usr/libexec/pcp/pmdas/trace/README
/usr/libexec/pcp/pmdas/trace/Remove
/usr/libexec/pcp/pmdas/trace/domain.h
/usr/libexec/pcp/pmdas/trace/help
/usr/libexec/pcp/pmdas/trace/pmdatrace
/usr/libexec/pcp/pmdas/trace/pmns
/usr/libexec/pcp/pmdas/trace/root
/usr/libexec/pcp/pmdas/trivial/Install
/usr/libexec/pcp/pmdas/trivial/Makefile
/usr/libexec/pcp/pmdas/trivial/README
/usr/libexec/pcp/pmdas/trivial/Remove
/usr/libexec/pcp/pmdas/trivial/domain.h
/usr/libexec/pcp/pmdas/trivial/help
/usr/libexec/pcp/pmdas/trivial/pmdatrivial.perl
/usr/libexec/pcp/pmdas/trivial/pmdatrivial.python
/usr/libexec/pcp/pmdas/trivial/pmns
/usr/libexec/pcp/pmdas/trivial/root
/usr/libexec/pcp/pmdas/trivial/trivial.c
/usr/libexec/pcp/pmdas/txmon/Install
/usr/libexec/pcp/pmdas/txmon/Makefile
/usr/libexec/pcp/pmdas/txmon/README
/usr/libexec/pcp/pmdas/txmon/Remove
/usr/libexec/pcp/pmdas/txmon/domain.h
/usr/libexec/pcp/pmdas/txmon/genload
/usr/libexec/pcp/pmdas/txmon/help
/usr/libexec/pcp/pmdas/txmon/pmns
/usr/libexec/pcp/pmdas/txmon/root
/usr/libexec/pcp/pmdas/txmon/txmon.c
/usr/libexec/pcp/pmdas/txmon/txmon.h
/usr/libexec/pcp/pmdas/txmon/txrecord.c
/usr/libexec/pcp/pmdas/unbound/Install
/usr/libexec/pcp/pmdas/unbound/Remove
/usr/libexec/pcp/pmdas/unbound/pmdaunbound.python
/usr/libexec/pcp/pmdas/weblog/Install
/usr/libexec/pcp/pmdas/weblog/README
/usr/libexec/pcp/pmdas/weblog/Remove
/usr/libexec/pcp/pmdas/weblog/check_match
/usr/libexec/pcp/pmdas/weblog/domain.h
/usr/libexec/pcp/pmdas/weblog/help
/usr/libexec/pcp/pmdas/weblog/pmdaweblog
/usr/libexec/pcp/pmdas/weblog/pmns
/usr/libexec/pcp/pmdas/weblog/root
/usr/libexec/pcp/pmdas/weblog/server.sh
/usr/libexec/pcp/pmdas/weblog/weblogconv.sh
/usr/libexec/pcp/pmdas/xfs/Install
/usr/libexec/pcp/pmdas/xfs/Remove
/usr/libexec/pcp/pmdas/xfs/domain.h
/usr/libexec/pcp/pmdas/xfs/help
/usr/libexec/pcp/pmdas/xfs/help.dir
/usr/libexec/pcp/pmdas/xfs/help.pag
/usr/libexec/pcp/pmdas/xfs/pmda_xfs.so
/usr/libexec/pcp/pmdas/xfs/pmdaxfs
/usr/libexec/pcp/pmdas/xfs/root
/usr/libexec/pcp/pmdas/xfs/root_xfs
/usr/libexec/pcp/pmdas/zfs/Install
/usr/libexec/pcp/pmdas/zfs/Remove
/usr/libexec/pcp/pmdas/zfs/domain.h
/usr/libexec/pcp/pmdas/zfs/help
/usr/libexec/pcp/pmdas/zfs/help.dir
/usr/libexec/pcp/pmdas/zfs/help.pag
/usr/libexec/pcp/pmdas/zfs/pmda_zfs.so
/usr/libexec/pcp/pmdas/zfs/pmdazfs
/usr/libexec/pcp/pmdas/zfs/root
/usr/libexec/pcp/pmdas/zfs/root_zfs
/usr/libexec/pcp/pmdas/zimbra/Install
/usr/libexec/pcp/pmdas/zimbra/Remove
/usr/libexec/pcp/pmdas/zimbra/pmdazimbra.pl
/usr/libexec/pcp/pmdas/zimbra/runaszimbra
/usr/libexec/pcp/pmdas/zimbra/zimbraprobe
/usr/libexec/pcp/pmdas/zswap/Install
/usr/libexec/pcp/pmdas/zswap/Remove
/usr/libexec/pcp/pmdas/zswap/pmdazswap.python
/usr/libexec/pcp/pmns/Make.stdpmid
/usr/libexec/pcp/pmns/Makefile
/usr/libexec/pcp/pmns/Rebuild
/usr/libexec/pcp/pmns/ReplacePmnsSubtree
/usr/libexec/pcp/pmns/lockpmns
/usr/libexec/pcp/pmns/root_denki
/usr/libexec/pcp/pmns/root_jbd2
/usr/libexec/pcp/pmns/root_kvm
/usr/libexec/pcp/pmns/root_linux
/usr/libexec/pcp/pmns/root_mmv
/usr/libexec/pcp/pmns/root_pmcd
/usr/libexec/pcp/pmns/root_pmproxy
/usr/libexec/pcp/pmns/root_podman
/usr/libexec/pcp/pmns/root_proc
/usr/libexec/pcp/pmns/root_root
/usr/libexec/pcp/pmns/root_xfs
/usr/libexec/pcp/pmns/root_zfs
/usr/libexec/pcp/pmns/stdpmid.local
/usr/libexec/pcp/pmns/stdpmid.pcp
/usr/libexec/pcp/pmns/unlockpmns

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pcp/2b643890566d601c71f17a60bade7af58bb1a331
/usr/share/package-licenses/pcp/34c5034377edef1080538bd0d4f5cf9b78e22dff
/usr/share/package-licenses/pcp/419ec3c0b11c7d22472ea99c03c347413a4ea406
/usr/share/package-licenses/pcp/488640bbc156f41a2d4c993008c5c72ddc4a1219
/usr/share/package-licenses/pcp/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/pcp/5d5da1000ec36c87ff28d1208cc89fa575f8675f
/usr/share/package-licenses/pcp/77b27c166eb1c7fa55288331b53f9c72b067e3c8
/usr/share/package-licenses/pcp/91c66db733cf0ff2b3216ec4223b940daf6b26d4
/usr/share/package-licenses/pcp/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/pcp/d097282eb6f05d825f591cef06bac3654b58feba
/usr/share/package-licenses/pcp/e9c1298de98016808910005a33de3a5f25dce05e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/KERNEL_PMDAS.1.gz
/usr/share/man/man1/PCPCompat.1.gz
/usr/share/man/man1/PCPIntro.1.gz
/usr/share/man/man1/PCP_KUBE_PODS.1.gz
/usr/share/man/man1/chkhelp.1.gz
/usr/share/man/man1/collectl2pcp.1.gz
/usr/share/man/man1/dbpmda.1.gz
/usr/share/man/man1/dbprobe.1.gz
/usr/share/man/man1/dstat.1.gz
/usr/share/man/man1/find-filter.1.gz
/usr/share/man/man1/ganglia2pcp.1.gz
/usr/share/man/man1/genload.1.gz
/usr/share/man/man1/genpmda.1.gz
/usr/share/man/man1/iostat2pcp.1.gz
/usr/share/man/man1/mkaf.1.gz
/usr/share/man/man1/mrtg2pcp.1.gz
/usr/share/man/man1/newhelp.1.gz
/usr/share/man/man1/pcp-atop.1.gz
/usr/share/man/man1/pcp-atopsar.1.gz
/usr/share/man/man1/pcp-collectl.1.gz
/usr/share/man/man1/pcp-dmcache.1.gz
/usr/share/man/man1/pcp-dstat.1.gz
/usr/share/man/man1/pcp-free.1.gz
/usr/share/man/man1/pcp-htop.1.gz
/usr/share/man/man1/pcp-iostat.1.gz
/usr/share/man/man1/pcp-ipcs.1.gz
/usr/share/man/man1/pcp-kube-pods.1.gz
/usr/share/man/man1/pcp-lvmcache.1.gz
/usr/share/man/man1/pcp-mpstat.1.gz
/usr/share/man/man1/pcp-numastat.1.gz
/usr/share/man/man1/pcp-pidstat.1.gz
/usr/share/man/man1/pcp-ps.1.gz
/usr/share/man/man1/pcp-python.1.gz
/usr/share/man/man1/pcp-shping.1.gz
/usr/share/man/man1/pcp-ss.1.gz
/usr/share/man/man1/pcp-summary.1.gz
/usr/share/man/man1/pcp-tapestat.1.gz
/usr/share/man/man1/pcp-uptime.1.gz
/usr/share/man/man1/pcp-verify.1.gz
/usr/share/man/man1/pcp-vmstat.1.gz
/usr/share/man/man1/pcp.1.gz
/usr/share/man/man1/pcp2graphite.1.gz
/usr/share/man/man1/pcp2json.1.gz
/usr/share/man/man1/pcp2spark.1.gz
/usr/share/man/man1/pcp2xml.1.gz
/usr/share/man/man1/pcp2zabbix.1.gz
/usr/share/man/man1/perfalloc.1.gz
/usr/share/man/man1/pmafm.1.gz
/usr/share/man/man1/pmcd.1.gz
/usr/share/man/man1/pmcd_wait.1.gz
/usr/share/man/man1/pmchart.1.gz
/usr/share/man/man1/pmclient.1.gz
/usr/share/man/man1/pmclient_fg.1.gz
/usr/share/man/man1/pmconfig.1.gz
/usr/share/man/man1/pmconfirm.1.gz
/usr/share/man/man1/pmcpp.1.gz
/usr/share/man/man1/pmdaactivemq.1.gz
/usr/share/man/man1/pmdaaix.1.gz
/usr/share/man/man1/pmdaapache.1.gz
/usr/share/man/man1/pmdabash.1.gz
/usr/share/man/man1/pmdabcc.1.gz
/usr/share/man/man1/pmdabind2.1.gz
/usr/share/man/man1/pmdabonding.1.gz
/usr/share/man/man1/pmdabpf.1.gz
/usr/share/man/man1/pmdabpftrace.1.gz
/usr/share/man/man1/pmdacifs.1.gz
/usr/share/man/man1/pmdacisco.1.gz
/usr/share/man/man1/pmdadarwin.1.gz
/usr/share/man/man1/pmdadbping.1.gz
/usr/share/man/man1/pmdadenki.1.gz
/usr/share/man/man1/pmdadm.1.gz
/usr/share/man/man1/pmdadocker.1.gz
/usr/share/man/man1/pmdads389.1.gz
/usr/share/man/man1/pmdads389log.1.gz
/usr/share/man/man1/pmdaelasticsearch.1.gz
/usr/share/man/man1/pmdafreebsd.1.gz
/usr/share/man/man1/pmdagfs2.1.gz
/usr/share/man/man1/pmdagluster.1.gz
/usr/share/man/man1/pmdagpfs.1.gz
/usr/share/man/man1/pmdagpsd.1.gz
/usr/share/man/man1/pmdahacluster.1.gz
/usr/share/man/man1/pmdahaproxy.1.gz
/usr/share/man/man1/pmdaib.1.gz
/usr/share/man/man1/pmdajbd2.1.gz
/usr/share/man/man1/pmdajson.1.gz
/usr/share/man/man1/pmdakvm.1.gz
/usr/share/man/man1/pmdalibvirt.1.gz
/usr/share/man/man1/pmdalinux.1.gz
/usr/share/man/man1/pmdalio.1.gz
/usr/share/man/man1/pmdalmsensors.1.gz
/usr/share/man/man1/pmdalogger.1.gz
/usr/share/man/man1/pmdalustre.1.gz
/usr/share/man/man1/pmdalustrecomm.1.gz
/usr/share/man/man1/pmdamailq.1.gz
/usr/share/man/man1/pmdamemcache.1.gz
/usr/share/man/man1/pmdamic.1.gz
/usr/share/man/man1/pmdammv.1.gz
/usr/share/man/man1/pmdamongodb.1.gz
/usr/share/man/man1/pmdamounts.1.gz
/usr/share/man/man1/pmdamssql.1.gz
/usr/share/man/man1/pmdamysql.1.gz
/usr/share/man/man1/pmdanamed.1.gz
/usr/share/man/man1/pmdanetbsd.1.gz
/usr/share/man/man1/pmdanetcheck.1.gz
/usr/share/man/man1/pmdanetfilter.1.gz
/usr/share/man/man1/pmdanews.1.gz
/usr/share/man/man1/pmdanfsclient.1.gz
/usr/share/man/man1/pmdanginx.1.gz
/usr/share/man/man1/pmdanutcracker.1.gz
/usr/share/man/man1/pmdanvidia.1.gz
/usr/share/man/man1/pmdaopenvswitch.1.gz
/usr/share/man/man1/pmdaoracle.1.gz
/usr/share/man/man1/pmdaoverhead.1.gz
/usr/share/man/man1/pmdapdns.1.gz
/usr/share/man/man1/pmdaperfevent.1.gz
/usr/share/man/man1/pmdapipe.1.gz
/usr/share/man/man1/pmdapodman.1.gz
/usr/share/man/man1/pmdapostfix.1.gz
/usr/share/man/man1/pmdapostgresql.1.gz
/usr/share/man/man1/pmdaproc.1.gz
/usr/share/man/man1/pmdarabbitmq.1.gz
/usr/share/man/man1/pmdaredis.1.gz
/usr/share/man/man1/pmdaroomtemp.1.gz
/usr/share/man/man1/pmdaroot.1.gz
/usr/share/man/man1/pmdarsyslog.1.gz
/usr/share/man/man1/pmdasamba.1.gz
/usr/share/man/man1/pmdasample.1.gz
/usr/share/man/man1/pmdasendmail.1.gz
/usr/share/man/man1/pmdashping.1.gz
/usr/share/man/man1/pmdasimple.1.gz
/usr/share/man/man1/pmdaslurm.1.gz
/usr/share/man/man1/pmdasmart.1.gz
/usr/share/man/man1/pmdasnmp.1.gz
/usr/share/man/man1/pmdasockets.1.gz
/usr/share/man/man1/pmdasolaris.1.gz
/usr/share/man/man1/pmdasummary.1.gz
/usr/share/man/man1/pmdasystemd.1.gz
/usr/share/man/man1/pmdate.1.gz
/usr/share/man/man1/pmdatrace.1.gz
/usr/share/man/man1/pmdatrivial.1.gz
/usr/share/man/man1/pmdatxmon.1.gz
/usr/share/man/man1/pmdaunbound.1.gz
/usr/share/man/man1/pmdaweblog.1.gz
/usr/share/man/man1/pmdawindows.1.gz
/usr/share/man/man1/pmdaxfs.1.gz
/usr/share/man/man1/pmdazfs.1.gz
/usr/share/man/man1/pmdazimbra.1.gz
/usr/share/man/man1/pmdazswap.1.gz
/usr/share/man/man1/pmdbg.1.gz
/usr/share/man/man1/pmdiff.1.gz
/usr/share/man/man1/pmdumplog.1.gz
/usr/share/man/man1/pmdumptext.1.gz
/usr/share/man/man1/pmerr.1.gz
/usr/share/man/man1/pmevent.1.gz
/usr/share/man/man1/pmfind.1.gz
/usr/share/man/man1/pmfind_check.1.gz
/usr/share/man/man1/pmgenmap.1.gz
/usr/share/man/man1/pmgetopt.1.gz
/usr/share/man/man1/pmhostname.1.gz
/usr/share/man/man1/pmie.1.gz
/usr/share/man/man1/pmie2col.1.gz
/usr/share/man/man1/pmie_check.1.gz
/usr/share/man/man1/pmie_daily.1.gz
/usr/share/man/man1/pmie_dump_stats.1.gz
/usr/share/man/man1/pmieconf.1.gz
/usr/share/man/man1/pmiectl.1.gz
/usr/share/man/man1/pmiestatus.1.gz
/usr/share/man/man1/pminfo.1.gz
/usr/share/man/man1/pmiostat.1.gz
/usr/share/man/man1/pmjson.1.gz
/usr/share/man/man1/pmlc.1.gz
/usr/share/man/man1/pmlock.1.gz
/usr/share/man/man1/pmlogcheck.1.gz
/usr/share/man/man1/pmlogconf.1.gz
/usr/share/man/man1/pmlogctl.1.gz
/usr/share/man/man1/pmlogdump.1.gz
/usr/share/man/man1/pmlogextract.1.gz
/usr/share/man/man1/pmlogger.1.gz
/usr/share/man/man1/pmlogger_check.1.gz
/usr/share/man/man1/pmlogger_daily.1.gz
/usr/share/man/man1/pmlogger_daily_report.1.gz
/usr/share/man/man1/pmlogger_merge.1.gz
/usr/share/man/man1/pmlogger_rewrite.1.gz
/usr/share/man/man1/pmloglabel.1.gz
/usr/share/man/man1/pmlogmv.1.gz
/usr/share/man/man1/pmlogpaste.1.gz
/usr/share/man/man1/pmlogreduce.1.gz
/usr/share/man/man1/pmlogrewrite.1.gz
/usr/share/man/man1/pmlogsize.1.gz
/usr/share/man/man1/pmlogsummary.1.gz
/usr/share/man/man1/pmmessage.1.gz
/usr/share/man/man1/pmmgr.1.gz
/usr/share/man/man1/pmnsadd.1.gz
/usr/share/man/man1/pmnsdel.1.gz
/usr/share/man/man1/pmnsmerge.1.gz
/usr/share/man/man1/pmpause.1.gz
/usr/share/man/man1/pmpost.1.gz
/usr/share/man/man1/pmprobe.1.gz
/usr/share/man/man1/pmproxy.1.gz
/usr/share/man/man1/pmpython.1.gz
/usr/share/man/man1/pmquery.1.gz
/usr/share/man/man1/pmrep.1.gz
/usr/share/man/man1/pmrepconf.1.gz
/usr/share/man/man1/pmsearch.1.gz
/usr/share/man/man1/pmseries.1.gz
/usr/share/man/man1/pmsignal.1.gz
/usr/share/man/man1/pmsleep.1.gz
/usr/share/man/man1/pmsnap.1.gz
/usr/share/man/man1/pmsocks.1.gz
/usr/share/man/man1/pmstat.1.gz
/usr/share/man/man1/pmstore.1.gz
/usr/share/man/man1/pmtime.1.gz
/usr/share/man/man1/pmtrace.1.gz
/usr/share/man/man1/pmval.1.gz
/usr/share/man/man1/pmwebd.1.gz
/usr/share/man/man1/sar2pcp.1.gz
/usr/share/man/man1/sheet2pcp.1.gz
/usr/share/man/man1/telnet-probe.1.gz
/usr/share/man/man1/txrecord.1.gz
/usr/share/man/man5/LOGARCHIVE.5.gz
/usr/share/man/man5/PMNS.5.gz
/usr/share/man/man5/labels.conf.5.gz
/usr/share/man/man5/mmv.5.gz
/usr/share/man/man5/pcp-atoprc.5.gz
/usr/share/man/man5/pcp-dstat.5.gz
/usr/share/man/man5/pcp-htop.5.gz
/usr/share/man/man5/pcp.conf.5.gz
/usr/share/man/man5/pcp.env.5.gz
/usr/share/man/man5/perfevent.conf.5.gz
/usr/share/man/man5/pmieconf.5.gz
/usr/share/man/man5/pmlogger.control.5.gz
/usr/share/man/man5/pmrep.conf.5.gz

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/pmcd.service
/usr/lib/systemd/system/pmfind.service
/usr/lib/systemd/system/pmfind.timer
/usr/lib/systemd/system/pmie.service
/usr/lib/systemd/system/pmie_check.service
/usr/lib/systemd/system/pmie_check.timer
/usr/lib/systemd/system/pmie_daily.service
/usr/lib/systemd/system/pmie_daily.timer
/usr/lib/systemd/system/pmie_farm.service
/usr/lib/systemd/system/pmie_farm_check.service
/usr/lib/systemd/system/pmie_farm_check.timer
/usr/lib/systemd/system/pmlogger.service
/usr/lib/systemd/system/pmlogger_check.service
/usr/lib/systemd/system/pmlogger_check.timer
/usr/lib/systemd/system/pmlogger_daily.service
/usr/lib/systemd/system/pmlogger_daily.timer
/usr/lib/systemd/system/pmlogger_farm.service
/usr/lib/systemd/system/pmlogger_farm_check.service
/usr/lib/systemd/system/pmlogger_farm_check.timer
/usr/lib/systemd/system/pmproxy.service
